### ISSUE TITLE
Google drive infected file

### ISSUE THREAD

**Issue by yobson1** [noahcoolboy/toucan-track#1]
Google drive has flagged this file [CL-Eye Platform SDK](https://drive.google.com/uc?export=download&id=1OIBxT0Q9KgjaOROA5y0bYfwK92jtEfTz) as infected and it can't be downloaded

**Comment by noahcoolboy** [comment]
Hello, thank you for having brought this to my attention.
I have uploaded the file to dropbox instead and the README has been updated.

Download: https://www.dropbox.com/s/7bxw2dlj0t88qj5/CL-Eye-Platform-SDK-1.6.4.0028.exe?dl=1
