### ISSUE TITLE
Very cool app.

### ISSUE THREAD

**Issue by AndrioJonatas** [noahcoolboy/toucan-track#3]
**_1 - You could compile an .exe for general users...
2 - Could make a fullbody version for general SteamVR
3 - Could create a "tag" webcam version for other purposes._**

Thanks!

**Comment by noahcoolboy** [comment]
Thank you for the feedback!
I'll take the suggestions into consideration.

**Comment by Obamafan1856** [comment]
just curious, how difficult would SteamVR integration be?  and was previously hoping i could use this for motion capture.
