### ISSUE TITLE
libusb: error [init_device] device 'USB\VID_... is no longer connected!

### ISSUE THREAD

**Issue by mikevador02** [noahcoolboy/toucan-track#9]
Hello,

Thanks for the nice project, 

Want to try to replace vives trackers with AI tracking free body with hight rate camera IR passtrought and see a google demo about tracking with blazepose/mediapie seem to be stable accurate. Like optitrack system but lower cost.
Your project is very in this range and we need to have one that working fine :) your seem very nice.

Other question you have added array with heavy model (this model is also included into your converted onnx models?)

So tried in the past kinect project (but not efficient).

My problem is : 

I try to launch it with webcam version also (insteal PS3 webcam) (later want to try it with RPI4 and V2/V3 high speed rate camera), but encounting a problem when i laught the calibtool.py (i have the windows but empty of list of webcam)

> libusb: error [init_device] device 'USB\VID_0BDA&PID_4014\2009xxxx1' is no longer connected!

I have checked about libusb version , is the (1.0.26b5) seem the last version installed.

I run on windows 11 (so i have checked also privacy settings about webcam).
I tried also to run as administrator python prompt launcher.

Maybe you can help, me but, i think is external problem about your code.

Best regards.

**Comment by noahcoolboy** [comment]
Hi! Thank you for your interest in Toucan Track.

The error seems to be caused by libusb, which is a library used by toucan track to interact with the PS3 Eye Cameras.
I believe this is not an issue with toucan track itself, but with your driver installation.

Have you followed the installation procedure correctly? Make sure the libusb drivers were installed and applied correctly.
If all goes well, when opening the device manager, you should see the following:
![image](https://github.com/noahcoolboy/toucan-track/assets/46800081/2a8a0c15-4a93-4f6f-b233-1366cad50541)

If this isn't the case, please try installing the drivers again.

**Comment by mikevador02** [comment]
Hello,

Thanks for your fast response, i try to use standard logitech usb webcam to test your project, so based on the modification proposed by ju1ce to use usb webcam.

So i think libusb normaly must work also for standart usb webcam, so my webcam is listed but said that not longer connected, think is timeout problem inside libusb maybe.

S between this time, i find your tuto about install libusb app on windows (other part like pip install) i will see

I continue to investigate, thanks for your message.

**Comment by noahcoolboy** [comment]
Hello again!

libusb is used in this project exclusively to interact with PS3 Eye cameras.
Support for other camera types is dependent on ju1ce's fork, and untested.
As I am not the author of the fork, I do not know their implementation and therefore cannot help you.
You will have to do some debugging and find a fix by modifying some of the code.
This shouldn't be too hard considering cv2 has support for most generic webcams, and toucan track is modular making it easy to add new features.

**Comment by mikevador02** [comment]
Hello,

Yes i understand better now on reading all impacts files, i had resolved problem with modify binding.py too, now your project begin to work with my usb cam, i will see later to make a full test.
And try to don't disturb you :) .

Thanks so much for your fast responses and this project.
